### ISSUE TITLE
Also support Python language in addition to Java. 

### ISSUE THREAD

**Issue by ajax711** [RubbaBoy/MSPaintIDE#8]

**Comment by RubbaBoy** [comment]
Thank you for your suggestion, I will look into this

**Comment by TheJayZ** [comment]
Thank you for your suggestion, I will look into this

**Comment by RubbaBoy** [comment]
After a short delay of 294 days, Python is now fully supported within the IDE, with syntax highlighting, diagnostics, and execution :)

The IDE isn't released yet and isn't really ready for others to work on quite yet due to being in a 'delicate' state per se, but the end is near, and you can have a proper IDE for your python programming very soon.
