### ISSUE TITLE
OCR Not working

### ISSUE THREAD

**Issue by arjvik** [RubbaBoy/MSPaintIDE#9]
Hi,
I am unable to use MSPaintIDE, even though it is the IDE of the gods.
When testing, in the highligted folder, I see that the OCR completely fails. Attached is a screenshot.
My file:
![main](https://user-images.githubusercontent.com/6262296/45395419-ae455c00-b5fb-11e8-9847-bf8b0ad89c5e.png)

OCR-ed image:
![main_highlighted](https://user-images.githubusercontent.com/6262296/45395413-a5ed2100-b5fb-11e8-990e-8e6e7ac73502.png)

**Comment by RubbaBoy** [comment]
Hello, thanks for your issue, may I ask what font and size you are using? One of the limitations is that you must be using Verdana with a size of 16. Here's an example of what your program rewritten in size 16 looks like, since the font looks correct, just looked like a sizing issue: ![](https://rubbaboy.me/images/t9xah3s)

**Comment by arjvik** [comment]
THANK YOU! That must have been the issue! I thought I did Verdana size 16 but apparently I messed up. I downloaded your image and it worked perfectly! Thank you very much!

**Comment by RubbaBoy** [comment]
No problem, I'm glad to have helped! I think you can also Ctrl + Scroll to change the font size, which has messed me up in the past.

Happy programming!
